# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision :shell, path: "VagrantfileProvision.sh"

  config.vm.synced_folder "../", "/vagrant"
  config.vm.network "private_network", ip: "1.2.3.4"
  config.vm.hostname = 'xivgear.local'

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.aliases = %w(
    xivgear.local
    xivgear.adminer
  )

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true

    vb.memory = "4096"
    vb.cpus = 2
  end
end
